`matriz=[[0,0,0],[0,0,0,]]
matriz[0][1]=int(input("dame el elemento[0][1]:"))
print(matriz)
matriz[0][0]=int(input("dame el elemento[0][0]:"))
print(matriz)
matriz[0][2]=int(input("dame el elemento[0][2]:"))
print(matriz)
matriz[1][0]=int(input("dame el elemento[1][0]:"))
print(matriz)
matriz[1][1]=int(input("dame el elemento[1][1]:"))
print(matriz)
matriz[1][2]=int(input("dame el elemento[1][2]:"))
print(matriz)
print("El elemneto del [0][0]es:",matriz[0],[0])
print("El elemneto del [0][1] es:",matriz[0],[1])
print("El elemneto del [0][2] es:",matriz[0],[2])
print("El elemneto del [1][0] es:",matriz[1],[0])
print("El elemneto del [1][1] es:",matriz[1],[1])
print("El elemneto del [1][2] es:",matriz[1],[2])`